version: '3.8'
services:
  db:
    image: postgres:16.3-alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=libraryfx
    ports:
      - '5435:5432'
    expose:
      - '5432'
    volumes:
      - db:/var/lib/postgresql/data
volumes:
  db:
    driver: local